 *********************************************************;
 * create a library to your "myfolders" directory;
 *********************************************************;

libname mydata '/folders/myfolders';

 *********************************************************;
 * copy the ageorionsdata dataset into your work directory;
 * just remember if you change the dataset to copy the updated
 * dataset back to your MYDATA library so you have the
 * updated dataset since the WORK library id deleted
 * when you exit SAS;
 *********************************************************;

data orions;
  set mydata.ageorionsdata;
  run;
  
 *********************************************************;
 * example Tasks/Graph/Histogram *;
 *********************************************************;
 /*
 *
 * Task code generated by SAS Studio 3.1 
 *
 * Generated on 'Sun Sep 14 2014 07:39:18 GMT-0400 (Eastern Standard Time)' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-431.11.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M1P12042013' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/main?locale=en_US&zone=GMT-04%3A00' 
 *
 */

/* Option group 5 (GRAPH SIZE) parameters. */
/*--Set Graph Size (in inches)--*/
ods graphics / reset width=6.4in height=4.8in imagemap;

/*--SGPLOT proc statement--*/
proc sgplot data=WORK.ORIONS;
    /*--Histogram settings--*/
    histogram Price /;

    /*--Vertical or Response Axis--*/
    yaxis grid;
run;

 *********************************************************;
 * example Tasks/Statistics/Distribution Analysis *;
 *********************************************************;
/*
 *
 * Task code generated by SAS Studio 3.1 
 *
 * Generated on 'Sun Sep 14 2014 07:40:25 GMT-0400 (Eastern Standard Time)' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-431.11.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M1P12042013' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/main?locale=en_US&zone=GMT-04%3A00' 
 *
 */

ods noproctitle;
ods select where=(lowcase(_path_) ? 'plot' or lowcase(_path_) ? 'gram');

proc univariate data=WORK.ORIONS noprint;
    histogram Price / normal kernel;
    inset mean median std var n / position=ne;
    probplot Price / normal(mu=est sigma=est);
    inset n / position=nw;
run;

 *********************************************************;
 * example Tasks/Graph/Scatter Plot *;
 *********************************************************;
/*
 *
 * Task code generated by SAS Studio 3.1 
 *
 * Generated on 'Sun Sep 14 2014 07:57:35 GMT-0400 (Eastern Standard Time)' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-431.11.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M1P12042013' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/main?locale=en_US&zone=GMT-04%3A00' 
 *
 */

/*--Set output size--*/
ods graphics / reset width=6.4in height=4.8in imagemap;

/*--SGPLOT proc statement--*/
proc sgplot data=WORK.ORIONS noautolegend;
    /*--TITLE and FOOTNOTE--*/
    title "Relationship Between Age and Price for Orion Cars";
    footnote j=l 
        "dataset taken from Introductory Statistics, 9th ed, Neil Weiss";

    /*--Scatter plot settings--*/
    scatter x=Age y=Price / markerattrs=(symbol=Circle color=CX0824f7 size=10) 
        transparency=0.00 name='Scatter';
    ;

    /*--X Axis--*/
    xaxis grid label="Age of Car";

    /*--Y Axis--*/
    yaxis grid label="Price of Car";
run;


 *********************************************************;
 * example Tasks/Statistics/Linear Regression *;
 *********************************************************;
/*
 *
 * Task code generated by SAS Studio 3.1 
 *
 * Generated on 'Sun Sep 14 2014 08:01:35 GMT-0400 (Eastern Standard Time)' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-431.11.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M1P12042013' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/main?locale=en_US&zone=GMT-04%3A00' 
 *
 */

ods noproctitle;

proc reg data=WORK.ORIONS alpha=0.05 plots(only)=(diagnostics residuals partial 
        fitplot observedbypredicted);
    model Price=Age / stb clb partial adjrsq;
    run;
quit;

 *********************************************************;
 * If the dataset had changed make a copy of the updated
 * datafile *;
 *********************************************************;

 * example of adding a variable to the dataset;
 
data orions2;
  set orions;
  newvar = 1; /* add a variable column of all 1s */
  run;
  
  * now save the updated dataset back into your library;
  
data mydata.orions2;
  set orions2;
  run;
  
data work.orions3;
  set orions;
  price_gt85 = price > 85;
  run;
  
proc logistic data=orions3 plots=all;
  model price_gt85 = age;
  run;
  
  
  
  
  
  